version: '3.8'

services:  
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: distributed_systems_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      app_network:
        ipv4_address: 172.25.0.2

  ubuntu-node-1:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: ubuntu-node-1
    environment:
      HOSTID: 1
      HOSTNAME: ubuntu-node-1
    depends_on:
      - postgres
    networks:
      app_network:
        ipv4_address: 172.25.0.3

  ubuntu-node-2:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: ubuntu-node-2
    environment:
      HOSTID: 2
      HOSTNAME: ubuntu-node-2
    depends_on:
      - postgres
    networks:
      app_network:
        ipv4_address: 172.25.0.4

  ubuntu-node-3:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: ubuntu-node-3
    environment:
      HOSTID: 3
      HOSTNAME: ubuntu-node-3
    depends_on:
      - postgres
    networks:
      app_network:
        ipv4_address: 172.25.0.5

  ubuntu-node-4:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: ubuntu-node-4
    environment:
      HOSTID: 4
      HOSTNAME: ubuntu-node-4
    depends_on:
      - postgres
    networks:
      app_network:
        ipv4_address: 172.25.0.6

  dbadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4 
    networks:
      app_network:
        ipv4_address: 172.25.0.7

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  db_data:
